### PR TITLE
debian buster uses default-mysql-client instead of mysql-client.

### PR DESCRIPTION
**Pull request by OskarStark**
Cherry picked from https://github.com/exozet/docker-php-fpm/pulls?q=is%3Apr+is%3Aclosed

### CODE REVIEW

**Comment by r3wald** [comment]
php:7.1.17-fpm seems to be the same as php:7.1.17-fpm-stretch.
But php:7.1.16 was built upon jessie, so there is no default-mysql-client (which was introduced with stretch).

**Comment by OskarStark** [comment]
Yes 😢gets more and more complicated.
Any idea how to solve this in an elegant way?

**Comment by DracoBlue** [comment]
I fixed that in https://github.com/exozet/docker-php-fpm/pull/95 in such way, that we use always -jessie suffixed builds. 

This works for all builds, except 7.1.31 :(. I will create a new branch for 7.1.31 afterwards.

**Comment by DracoBlue** [comment]
In https://github.com/exozet/docker-php-fpm/pull/122 I do sed for default- in case of non jessie distros now.

**Pull request closed without merging**
