### PR TITLE
Clean apt lists directory

### PR DESCRIPTION
**Pull request by hoffigk**
Clean apt lists directory to avoid caching issues for further apt-get…

Before, the following error occured on an additional "apt-get update":

E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)

Steps to reproduce the error:

```
docker run exozet/php-fpm:7.2 bash -c "apt-get update"
```

### CODE REVIEW

**Comment by DracoBlue** [comment]
Thx! LGTM.

@OskarStark what do you think?

**Comment by OskarStark** [comment]
👍🏻 and less image size 😊

**Comment by hoffigk** [comment]
Why are the [builds](https://travis-ci.org/exozet/docker-php-fpm/jobs/491809452#L470) fail? 

If i run the build process on a fresh install all is fine.

```
export PHP_VERSION=7.3.1
export PHP_VERSION_ALIAS=7.3

./build_version.sh $PHP_VERSION
Pull latest php:7.3.1-fpm
Building exozet/php-fpm:7.3.1
Building exozet/php-fpm:7.3.1-sudo
Building exozet/php-fpm:7.3.1-root
```

**Comment by hacfi** [comment]
> 👍🏻 and less image size 😊

Only if you would run it in the same `RUN` instructions as the `apt-get update`.

**Comment by OskarStark** [comment]
You are right, but this is not possible unless we do alle apt-get commands in a row but this would be to noisy and result in a less structured Dockerfile. Lets keep it like this!

**Comment by OskarStark** [comment]
Please rebase

**Comment by hoffigk** [comment]
I can't reproduce the error anymore. Perhaps the problem was the apt repository. This is strange ... So i think this PR is no longer needed.

**Comment by OskarStark** [comment]
Let’s close it for now, less code to maintain.
Reopen if error occurs again, fine?

**Comment by hoffigk** [comment]
Let's close this PR.

If this error occurs again, we reopen it.

**Pull request closed without merging**
