### PR TITLE
Added 7.4.13

### PR DESCRIPTION
**Pull request by hoffigk**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Offtopic, but are you open for a PHP 8 PR? 😄

**Comment by hoffigk** [comment]
> Offtopic, but are you open for a PHP 8 PR?

Sure. But it still takes a little while :)

**Comment by niepi** [comment]
> Offtopic, but are you open for a PHP 8 PR? 😄

I look at this too over the holidays, but the build failed for me, because the rabbitmq deps where not working with php8 until now

**Comment by DracoBlue** [comment]
Php8 chat https://github.com/exozet/docker-php-fpm/issues/187

**Pull request merged**
