### PR TITLE
Release/8.2

### PR DESCRIPTION
**Pull request by niepi**

### CODE REVIEW

**Comment by niepi** [comment]
this is still WIP
- upgraded to pcov 1.0.11
- upgraded to xdebug 3.2.0alpha2
- on alpine socket extension fails on build

**Comment by DracoBlue** [comment]
added sockets ;)

**Comment by DracoBlue** [comment]
@niepi @OskarStark alpine pecl xdebug2.3.0 fails :(

**Comment by DracoBlue** [comment]
added the missing linux-headers package for xdebug build. let's see how this wents ;)

**Review by niepi — COMMENTED** [review]
looks good to me

**Comment by DracoBlue** [comment]
Thanks a lot @niepi !

**Comment by niepi** [comment]
@DracoBlue thx for your support

**Pull request merged**
