### PR TITLE
Support arm64 in php 8.1

### PR DESCRIPTION
**Pull request by eerison**
MicrosoftTeams-image (1)

add the support for platform `linux/arm64`

### CODE REVIEW

**Comment by DracoBlue** [comment]
Any comments from @niepi @OskarStark or @llupa on this?

**Comment by OskarStark** [comment]
It is indeed more specific, but I hadn't any issues in the past and it increases complexity, not sure its worth.

Up to you @DracoBlue

**Comment by OskarStark** [comment]
Btw. why is it a draft PR? 🤔

**Comment by niepi** [comment]
I'm also not in favour on this. The added complexity, is probably not worth it.

**Comment by DracoBlue** [comment]
I started some description at https://github.com/exozet/docker-php-fpm/wiki/Draft-for-new-Structure to figure a new structure for tags etc - not finished, only a draft!

**Comment by niepi** [comment]
@DracoBlue  @OskarStark  I would be in favour on closing this.

we support arm on https://github.com/Endava/docker-php

**Comment by eerison** [comment]
As it's maintained in other repository, I'm closing this PR ;)

**Pull request closed without merging**
