### PR TITLE
upgrade to xdebug3

### PR DESCRIPTION
**Pull request by Arconian**
This PR:

- upgrades Xdebug to version 3.1.6
- updates Xdebug related Env variables and Xdebug config to support xdebug3

### CODE REVIEW

**Comment by niepi** [comment]
@Arconian Can you please move the composer upgrade to a separate PR

**Comment by Arconian** [comment]
Done, forgot it in the alpine version anyways 🤦

**Comment by llupa** [comment]
Can you please add the "stuff" in the README too? They still showcase how to use XDebug 2. I will approve it asap afterwards

**Comment by llupa** [comment]
@DracoBlue Just to verify, I think we did not want to do it for PHP7 before? Is this PR ok, or should it also behave with both?

**Comment by Arconian** [comment]
Valid point @llupa https://xdebug.org/docs/compat#versions looks like there might be problems with xdebug 3.1 on Windows. I will set the xdebug version to the latest 3.0.x then, to be safe.

**Comment by Arconian** [comment]
After further discussion we came to a conclusion that switching to xdebug3 will be a breaking change and thus should not be done. So now the idea is to add additional tags for php7.4 with xdebug3 so that everyone can decide image with which xdebug version they should get. Do you think it might be a reasonable solution?

**Comment by DracoBlue** [comment]
IMHO: We won't merge xdebug3 support into 7.x as a breaking change.

Please upgrade your project to php8 OR run pecl install xdebug in your custom Dockerfile to upgrade xdebug if you need it in php7.x.

**Pull request closed without merging**
