### PR TITLE
Add imagick extension

### PR DESCRIPTION
**Pull request by patrickmaynard**
I have only added the imagick extension for php 5.x containers. I don't believe our php 7.x applications use it.

### CODE REVIEW

**Comment by OskarStark** [comment]
Why not doing this instead? (this works for PHP 7 in my case, you need to try PHP 5)
```
# imagick
RUN apt-get install -y libmagickwand-dev \
    && pecl install imagick \
    && docker-php-ext-enable imagick
```

and I am 👍  to add this to both PHP version, WDYT @DracoBlue ?

Please add extension to the README

**Comment by DracoBlue** [comment]
Yep. Please use @OskarStark‘s way.

**Comment by patrickmaynard** [comment]
Oskar's version works for 5.5 and 5.6 as well, based on the results I see when running this test:

https://stackoverflow.com/a/22438898/8252915

(No text shows up, but I think that is a configuration issue rather than a problem with the library itself, since this is true in all cases.)

I will add Oskar's way to all four versions.

**Comment by OskarStark** [comment]
@patrickmaynard could you squash your commits into one?

otherwise we could do this for you while merging

**Comment by DracoBlue** [comment]
@OskarStark I sqashed the commits on my own.

**Comment by DracoBlue** [comment]
@patrickmaynard thanks for the PR!

**Comment by DracoBlue** [comment]
It was missing for php 7.1, though :(. I added it right after merging to master.

**Pull request merged**
