### PR TITLE
Added 7.3.25

### PR DESCRIPTION
**Pull request by hoffigk**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by hoffigk** [comment]
I hope that this commit will fix the major.minor image, because this image contains not the newest php version. Before this PR the version must be 7.3.24.

```
docker pull exozet/php-fpm:7.3-sudo 
7.3-sudo: Pulling from exozet/php-fpm
Digest: sha256:5b1358f24edcf98e86f3f1d65502709f9ae35acb82c4285bd00e3b22261bff99
Status: Image is up to date for exozet/php-fpm:7.3-sudo
docker.io/exozet/php-fpm:7.3-sudo
```

See the version number:

```
docker run --rm exozet/php-fpm:7.3-sudo php -v 
PHP 7.3.22 (cli) (built: Sep 10 2020 14:31:39) ( NTS )
```

**Comment by hoffigk** [comment]
I hope that this commit will fix the major.minor image, because this image contains not the newest php version. Before this PR the version must be 7.3.24.

```
docker pull exozet/php-fpm:7.3-sudo 
7.3-sudo: Pulling from exozet/php-fpm
Digest: sha256:5b1358f24edcf98e86f3f1d65502709f9ae35acb82c4285bd00e3b22261bff99
Status: Image is up to date for exozet/php-fpm:7.3-sudo
docker.io/exozet/php-fpm:7.3-sudo
```

See the version number:

```
docker run --rm exozet/php-fpm:7.3-sudo php -v 
PHP 7.3.22 (cli) (built: Sep 10 2020 14:31:39) ( NTS )
```

**Comment by OskarStark** [comment]
Lets see 👍

**Comment by hoffigk** [comment]
The exozet/php-fpm:7.3-sudo is not updated :(

Bildschirmfoto vom 2021-01-05 10-46-38

**Comment by OskarStark** [comment]
@DracoBlue can you please have a look, not so much time right now

**Pull request merged**
