### PR TITLE
[WIP] only build relevant Dockerfiles

### PR DESCRIPTION
**Pull request by OskarStark**
a README change would result in:
screenshot 2018-12-23 13 46 44

A change in Dockerfile 7.3 would result in:

This would not affect a merge into `master` (where everything will be build, regardless of the relevant files)

### CODE REVIEW

**Comment by OskarStark** [comment]
> Any way to avoid the matrix build entirely? Maybe building all builds in one job if we are on a branch?

What do you mean? before it was the same like yet or is your goal to change the current behavior?

**Comment by DracoBlue** [comment]
I woul like to make building PRs faster, by having exactly one job building all affected images. But master always builds all of them in seperate jobs.

**Comment by OskarStark** [comment]
That’s exactly the goal of this pr

**Comment by DracoBlue** [comment]
Yup. But still all jobs are triggered at travis. ;)

**Comment by OskarStark** [comment]
They will be triggered but should not be executed, but still wip and not working as expected

**Comment by DracoBlue** [comment]
That’s why I was thinking about two matrix configs:

1. on everything except master, trigger one special job which executes all affected php versions 
2. on master, trigger on job for each php version

**Comment by OskarStark** [comment]
Currently no time to work on

**Pull request closed without merging**
